Rewrite secret creation logic

diff --git a/authelia/rootfs/etc/s6-overlay/s6-rc.d/init-authelia/run b/authelia/rootfs/etc/s6-overlay/s6-rc.d/init-authelia/run
--- a/authelia/rootfs/etc/s6-overlay/s6-rc.d/init-authelia/run
+++ b/authelia/rootfs/etc/s6-overlay/s6-rc.d/init-authelia/run
@@ -7,6 +7,51 @@
 
 bashio::log.debug "Initializing Authelia environment variables..."
 
+# Generate secrets
+bashio::log.debug "Starting Authelia secrets check..."
+
+# Define secrets path
+SECRETS_PATH="/data/secrets"
+
+if ! bashio::fs.directory_exists "$SECRETS_PATH"; then
+
+    JWT_SECRET_FILE="/data/secrets/jwt_secret"
+    if authelia crypto rand --length 64 --charset ascii --file "$JWT_SECRET_FILE"; then
+        bashio::log.info "JWT secret generated and stored at $JWT_SECRET_FILE."
+    else
+        bashio::log.error "Failed to generate JWT secret!"
+        exit 1
+    fi
+
+    # Debug output for the JWT secret path
+    bashio::log.debug "JWT Secret File: $AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE"
+
+    SESSION_SECRET_FILE="/data/secrets/session_secret"
+    if authelia crypto rand --length 64 --charset ascii --file "$SESSION_SECRET_FILE"; then
+        bashio::log.info "Session secret generated and stored at $SESSION_SECRET_FILE."
+    else
+        bashio::log.error "Failed to generate Session secret!"
+        exit 1
+    fi
+
+    # Debug output for the Session secret path
+    bashio::log.debug "Session Secret File: $AUTHELIA_SESSION_SECRET_FILE"
+
+    STORAGE_SECRET_FILE="/data/secrets/storage_encryption_key"
+        if authelia crypto rand --length 64 --charset ascii --file "$STORAGE_SECRET_FILE"; then
+            bashio::log.info "Storage encryption key generated and stored at $STORAGE_SECRET_FILE."
+        else
+            bashio::log.error "Failed to generate Storage encryption key!"
+            exit 1
+        fi
+
+        # Debug output for the Session secret path
+        bashio::log.debug "Storage Secret File: $STORAGE_SECRET_FILE"
+
+else
+    bashio::log.debug "Secrets folder already exists. Skipping generation."
+fi
+
 bashio::log.debug "Starting Authelia configuration check..."
 
 # Define paths
@@ -38,53 +83,6 @@ if ! bashio::fs.file_exists "$CONFIG_FILE"; then
             -template /etc/s6-overlay/s6-rc.d/init-authelia/users.gtpl \
             -out /config/users.yml
     bashio::log.debug "users.yml generated successfully."
-
-    # Generate secrets
-
-    JWT_SECRET_FILE="/data/secrets/jwt_secret"
-    if [[ ! -f "$JWT_SECRET_FILE" ]]; then
-        bashio::log.debug "JWT secret not found. Generating a new one..."
-        if authelia crypto rand --length 64 --charset ascii --file "$JWT_SECRET_FILE"; then
-            bashio::log.info "JWT secret generated and stored at $JWT_SECRET_FILE."
-        else
-            bashio::log.error "Failed to generate JWT secret!"
-            exit 1
-        fi
-    else
-        bashio::log.debug "JWT secret already exists at $JWT_SECRET_FILE. Skipping generation."
-    fi
-
-    # Debug output for the JWT secret path
-    bashio::log.debug "JWT Secret File: $AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE"
-
-    SESSION_SECRET_FILE="/data/secrets/session_secret"
-    if [[ ! -f "$SESSION_SECRET_FILE" ]]; then
-        bashio::log.debug "Session secret not found. Generating a new one..."
-        if authelia crypto rand --length 64 --charset ascii --file "$SESSION_SECRET_FILE"; then
-            bashio::log.info "Session secret generated and stored at $SESSION_SECRET_FILE."
-        else
-            bashio::log.error "Failed to generate Session secret!"
-            exit 1
-        fi
-    else
-        bashio::log.debug "Session secret already exists at $SESSION_SECRET_FILE. Skipping generation."
-    fi
-
-    # Debug output for the Session secret path
-    bashio::log.debug "Session Secret File: $AUTHELIA_SESSION_SECRET_FILE"
-
-    STORAGE_SECRET_FILE="/data/secrets/storage_encryption_key"
-    if [[ ! -f "$STORAGE_SECRET_FILE" ]]; then
-        bashio::log.debug "Storage encryption key not found. Generating a new one..."
-        if authelia crypto rand --length 64 --charset ascii --file "$STORAGE_SECRET_FILE"; then
-            bashio::log.info "Storage encryption key generated and stored at $STORAGE_SECRET_FILE."
-        else
-            bashio::log.error "Failed to generate Storage encryption key!"
-            exit 1
-        fi
-    else
-        bashio::log.debug "Storage encryption key already exists at $STORAGE_SECRET_FILE. Skipping generation."
-    fi
 
     # Debug output for the Storage secret path
     bashio::log.debug "Storage Secret File: $AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE"
